//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ASPSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public long AdminID { get; set; }
        [Required(ErrorMessage = "Please enter email address")]
        [RegularExpression(@"[a-zA-Z0-9\.]*@iit.du.ac.bd", ErrorMessage = "Enter iit domain email address")]
        public string AdminEmail { get; set; }
        [Required(ErrorMessage = "Please enter name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter password")]
        [StringLength(12, MinimumLength = 4)]
        public string Password { get; set; }
        public string Address { get; set; }
        public string Religion { get; set; }
        public string BloodGroup { get; set; }
        public string Gender { get; set; }
        [RegularExpression(@"^[0-9]{11}$", ErrorMessage = "Enter 11 digit mobile number")]
        public string MobileNumber { get; set; }
    }
}
