//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ASPSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public long ContentID { get; set; }
        [Required]
        public long StudentID { get; set; }
        [Required]
        public string ContentPath { get; set; }
        [Required(ErrorMessage = "Please select type of file example: project, document")]
        public string ContentType { get; set; }
        [Required(ErrorMessage = "Add some description")]
        public string ContentDescription { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
