//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public long AdminID { get; set; }
        public string AdminEmail { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Religion { get; set; }
        public string BloodGroup { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> MobileNumber { get; set; }
    }
}
