//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public long ContentID { get; set; }
        public long StudentID { get; set; }
        public string ContentPath { get; set; }
        public string ContentType { get; set; }
        public string ContentDescription { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
