//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRecommendation
    {
        public long ContentID { get; set; }
        public long FacultyID { get; set; }
        public long StudentID { get; set; }
        public long CourseID { get; set; }
        public Nullable<int> CourseRating { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Student Student { get; set; }
    }
}
