//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRecommendation
    {
        public string FacultyEmail { get; set; }
        public string FacultyEmail { get; set; }
        public string CourseNumber { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
